create extension if not exists pgcrypto;
create type public.user_role as enum ('ADMIN','SALESPERSON');
create type public.order_status as enum ('NEW','CONFIRMED','DESIGN','PRODUCTION','READY','DELIVERY','DELIVERED','ON_HOLD','CANCELLED');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,role public.user_role not null default 'SALESPERSON',created_at timestamptz not null default now());
create table public.customers(id uuid primary key default gen_random_uuid(),name text not null,phone text not null,address text,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.orders(id uuid primary key default gen_random_uuid(),invoice text not null unique,customer_id uuid not null references public.customers(id),salesperson_id uuid references public.profiles(id),order_date date not null default current_date,delivery_date date,source text,priority text not null default 'Normal',status public.order_status not null default 'NEW',total_amount numeric(12,2) not null default 0,advance numeric(12,2) not null default 0,due_amount numeric(12,2) not null default 0,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_name text not null,quantity integer not null default 0,unit_price numeric(12,2) not null default 0,created_at timestamptz not null default now());
create table public.payments(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,amount numeric(12,2) not null,method text,paid_at timestamptz not null default now(),note text,created_by uuid references public.profiles(id));
create table public.order_status_history(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,from_status public.order_status,to_status public.order_status not null,changed_by uuid references public.profiles(id),changed_at timestamptz not null default now());
create table public.order_notes(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,note text not null,created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table public.activities(id uuid primary key default gen_random_uuid(),order_id uuid references public.orders(id) on delete cascade,customer_id uuid references public.customers(id),actor_id uuid references public.profiles(id),action text not null,details jsonb,created_at timestamptz not null default now());
create table public.google_accounts(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,email text,provider_account_id text,access_token_encrypted text,refresh_token_encrypted text,created_at timestamptz not null default now());
create table public.google_drive_folders(id uuid primary key default gen_random_uuid(),google_account_id uuid not null references public.google_accounts(id) on delete cascade,name text not null,drive_folder_id text not null,drive_url text,parent_drive_folder_id text,created_at timestamptz not null default now());
create table public.order_files(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,google_account_id uuid references public.google_accounts(id),drive_folder_id text,drive_file_id text not null,file_name text not null,file_url text,note text,uploaded_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table public.deliveries(id uuid primary key default gen_random_uuid(),order_id uuid not null unique references public.orders(id) on delete cascade,delivery_date date,phone text,name text,address text,cod numeric(12,2) not null default 0,status text not null default 'PENDING',created_at timestamptz not null default now());
create table public.steadfast_orders(id uuid primary key default gen_random_uuid(),order_id uuid not null unique references public.orders(id) on delete cascade,consignment_id text,tracking_code text,status text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.odoo_contacts(id uuid primary key default gen_random_uuid(),customer_id uuid not null unique references public.customers(id) on delete cascade,odoo_contact_id text,odoo_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete cascade,title text not null,message text not null,read_at timestamptz,created_at timestamptz not null default now());
create index orders_delivery_date_idx on public.orders(delivery_date);
create index orders_status_idx on public.orders(status);
create index orders_customer_idx on public.orders(customer_id);
create index customers_phone_idx on public.customers(phone);

alter table public.profiles enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;
alter table public.order_status_history enable row level security;
alter table public.order_notes enable row level security;
alter table public.activities enable row level security;
alter table public.google_accounts enable row level security;
alter table public.google_drive_folders enable row level security;
alter table public.order_files enable row level security;
alter table public.deliveries enable row level security;
alter table public.steadfast_orders enable row level security;
alter table public.odoo_contacts enable row level security;
alter table public.notifications enable row level security;

create or replace function public.is_admin() returns boolean language sql stable as $$ select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='ADMIN') $$;
create policy "profiles own or admin" on public.profiles for select using (id=auth.uid() or public.is_admin());
create policy "users see customers" on public.customers for select using (public.is_admin() or created_by=auth.uid());
create policy "users insert customers" on public.customers for insert with check (created_by=auth.uid());
create policy "users update customers" on public.customers for update using (public.is_admin() or created_by=auth.uid());
create policy "users see orders" on public.orders for select using (public.is_admin() or salesperson_id=auth.uid());
create policy "users insert orders" on public.orders for insert with check (salesperson_id=auth.uid());
create policy "users update orders" on public.orders for update using (public.is_admin() or salesperson_id=auth.uid());
create policy "users see order items" on public.order_items for select using (exists(select 1 from public.orders o where o.id=order_id and (o.salesperson_id=auth.uid() or public.is_admin())));
create policy "users manage order items" on public.order_items for all using (exists(select 1 from public.orders o where o.id=order_id and (o.salesperson_id=auth.uid() or public.is_admin()))) with check (exists(select 1 from public.orders o where o.id=order_id and (o.salesperson_id=auth.uid() or public.is_admin())));
